# Generated by Django 6.0.2 on 2026-02-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('cabriolet', 'Cabriolet'), ('minivan', 'Minivan'), ('truck', 'Truck')], default='sedan', max_length=20, null=True, verbose_name='Type of Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(upload_to='car_images'),
        ),
    ]
